server:
  port: 8500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: localhost
spring:
  application:
    name: product
