spring:
  application:
    name: config
#  cloud:
#    config:
#      server:
#        git:
#          username: username #git账号
#          password: password #git密码
#          uri: address #远程git地址
#          basedir: /data/ #文件
eureka:
  instance:
#    instance-id: config
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
server:
  port: 8555
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    bus-refresh:
#      enabled: true
#      base-path: /actuator
logging:
  level:
    org.springframework.cloud.bus: debug
