spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          username: username
          password: password
          uri: address
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8555