server:
  port: 8763
spring:
  application:
    name: eureka-server
  profiles:
    active: dev63
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8761/eureka,http://${spring.security.user.name}:${spring.security.user.password}@peer2:8762/eureka
    #注册中心的职责是维护服务实力，不需要去检索服务
    fetch-registry: true
    #该应用为注册中心，不需要注册自己
    register-with-eureka: true
  instance:
    hostname: peer3
    appname: server-eureka
