server:
  port: 8762
spring:
  application:
    name: eureka2
eureka:
  client:
    #指向与本地实例相同的主机
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8763/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #注册中心的职责是维护服务实力，不需要去检索服务
    fetch-registry: false
    #该应用为注册中心，不需要注册自己
    register-with-eureka: false
  instance:
    instance-id: localhost
    hostname: localhost
